dist: xenial
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.cache/pip"
  - "$HOME/miniconda3"
branches:
  only:
  - master
  - development
  - "/^[vV]?\\d+\\.\\d+\\.\\d+$/"
before_install: unset _JAVA_OPTIONS
install:
- "$HOME/miniconda3/bin/conda --version || ./.install-reports-dependencies.sh"
before_script: if [ "$VAADIN_CHARTS_LICENSE_CODE" != "" ]; then echo "$VAADIN_CHARTS_LICENSE_CODE"
  > ~/.vaadin.charts.developer.license; fi;
script: mvn --quiet --activate-profiles !development-build,!release-build --settings
  .travis.settings.xml clean cobertura:cobertura package
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings
    .travis.settings.xml deploy -DskipITs
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles !development-build,release-build --settings
    .travis.settings.xml deploy -DskipITs
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true
after_deploy:
- echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && source ~/.bashrc
  && conda activate qbic-docs-build
- mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml
  site
- ./.generate-reports.py $TRAVIS_BRANCH $TRAVIS_REPO_SLUG "[skip travis] Updated gh-pages"
  "This commit was performed from travis-ci.com using a personal access key" "Build
  ID $TRAVIS_BUILD_ID" "Job ID TRAVIS_JOB_ID" "Branch $TRAVIS_BRANCH" "Log of this
  build found at $TRAVIS_JOB_WEB_URL"
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
    rooms:
    - secure: "***"
env:
  global:
  - secure: MgdsQH+fj6DqKY7RKVSdChACiwrR0yaf23oYqO+v6rA6pY74FxI9JU7FEH8t2qufPggyMw6C+M5g3CKkTjQANrWMNKP4IFFQF/vev2BWMwQwcEjLaowHoXz948yPErtiHehC+Sv5S+TjsMd/A+Yl9OJQqYoNkCPTDRpplmdfJH6eB/bYeGWFF9kWzMRSH33OPQX0vRptSPlapVLwNGIGRfaepX43IppX9ThYi45k9CzDutnHhuIIi8sDlQ/XELYZg4A08blo+eGHYoIG6axGah4rahEmUH6VFUXBjl7+35y2WJVhfqyhF/lQIB9glIvQrYdiOdkceNVYa02iZk7L5KdmVo9uLWlKRrfFfWEIn3qZ41d3djTnPy89FU3qCEeTc4sqNU+dRJRwHvu3BBBqGdUbp6Y5pKajXHDsw/jI33oNZwWb9Av6yt1QVVSURNDxVltRNQa1BRJOGhy8//aiJRMWYyV3X2L6W4/bDZ+eZg9IP6j2fZiFGU+YBmu80fZCgGCXMzKiGrc8LmaZP8QfjDytveKww5+egipjEzKh1UGlmT1pZ5NF607IUq1GhdaR3tG3O3qkN0yxfQTjgmerc8I633XTB99HE7xW6azJCpbsfyj1Ak16tXM/0SKL1PnIoI+VGNl0MRMa6bQESa1qZ4NKprXbdHt6fGWLdGIXH+s=
  - secure: tBbkoDku3J1HB2NVn8szrSqHGPejxq5tPScY88bangHlOS/rMpm/a9CsiUpc4U1HN1oiAaEehm6jvR++brrQrrhcnk8FLwBSXvsw4aQGx8sE8XXzqg9AFkDKdTsK1QiE9YguFjhx8G6Mq7gsOstefCxYjmRMbY5ya4uj91siTftCo5qXfTiHIjCAzoVE/UaHti6yRvCUcxD88PozGkJZ93Lg01qnAycoGMtW7+VmGCBADWv9ktgvdj2fvSP9ypf6EdGbtrjWykJdYG6PNfItBHQ2gvNP99OkoUgppG4czMGM+h1wH7tCsbP3lBJBTIm9yd3DDNQNegRPOnCmYWZ75X3Bbet2IUjXzyIdPQ8IdWycxKOpvla62/iqZZIf3/WHv06DyPC0c1JblAUTkG+MaNJE2WsWeYPygYeX/PAq1dzVnTGX2f2oGaZvC4w3Z993WTvzLdYD/Td8MdjgrGwIHcAly4/utYQpIVrMDGqJWQ01FHAlyNngHeqjkQKMUuTBVosIj4S3QIHYfsQ1NBjTw4QOke2IJGt0hik4ikEKy4ExWZ8sT2mE+YG5mx96G3tI4NdK0TvmHJOmuNhtCGQacW1uzcbQbC56xb6TGRNvvoBcP1DNJhP6lFNFwL6gmBDNL+RWNVB6/U9+YUSHCY5SL2TRCINo5PAJAvXzpYL5Kqc=
